name: Test code builds images and pushes to docker hub

on: [push]

jobs:
  build:
    name: build shit
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Creating test client image
        run: docker build -t client_test -f client/Dockerfile.dev client
      - name: run client test
        run: docker run -e CI=true client_test npm test

      - name: Login to GH Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUSH_CONTAINER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push client to GH Reg
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: client/Dockerfile
          push: true
          tags: ghcr.io/rotendahl/kubernetes-test/client:latest

      - name: Push Server to GH Reg
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: server/Dockerfile
          push: true
          tags: ghcr.io/rotendahl/kubernetes-test/server:latest

      - name: Push Worker to GH Reg
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          file: worker/Dockerfile
          push: true
          tags: ghcr.io/rotendahl/kubernetes-test/worker:latest

      - name: Push Nginx to GH Reg
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: worker/Dockerfile
          push: true
          tags: ghcr.io/rotendahl/kubernetes-test/nginx:latest