name: Test code builds images and pushes to docker hub

on: [push]

jobs:
  test:
    name: build shit
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GH Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUSH_CONTAINER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push client to GH Reg
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: client/Dockerfile
          push: true
          tags: |
            ghcr.io/rotendahl/kubernetes-test/client:latest
            ghcr.io/rotendahl/kubernetes-test/client:$(git rev-parse --short HEAD)

      - name: Push Server to GH Reg
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: server/Dockerfile
          push: true
          tags: ghcr.io/rotendahl/kubernetes-test/server:latest

      - name: Push Worker to GH Reg
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          file: worker/Dockerfile
          push: true
          tags: ghcr.io/rotendahl/kubernetes-test/worker:latest

      - name: test sha
        run: echo "commit-$(git rev-parse --short HEAD)"